const ACCOUNT='0xd42A3Ac56456bD5422835B36C35Cacb6448ddCd9';
const API='https://api.arcadia.finance/v1/api';
const WETH='0x4200000000000000000000000000000000000006';
const GT='https://api.geckoterminal.com/api/v2';
const STABLES=new Set(['0x833589fcd6edb6e08f4c7c32d4f71b54bda02913','0x60a3e35cc302bfa44cb288bc5a4f316fdb1adb42','0xfde4c96c8593536e31f229ea8f37b2adac5a7b8','0x4e65fe4dba92790696d040ac24aa414708f5c0ab']);
async function arc(path){const r=await fetch(`${API}${path}`,{headers:{Accept:'application/json','User-Agent':'JDV-Arcadia-LP-Tracker/1.5'}});if(!r.ok)throw new Error(`Arcadia data error ${r.status}`);return r.json()}
async function gt(path){const r=await fetch(`${GT}${path}`,{headers:{Accept:'application/json','User-Agent':'JDV-Arcadia-LP-Tracker/1.5'}});if(r.ok)return r.json();throw new Error(`Market data error ${r.status}`)}
function tokenAddress(rel){return rel?.data?.id?.split('_').pop()?.toLowerCase()||''}
function activityScore(pool){const a=pool.attributes||{};return Number(a.volume_usd?.m15||0)*10+Number(a.volume_usd?.h1||0)+Number(a.reserve_in_usd||0)*.001}
function parseTrade(t){const a=t?.attributes||{},from=(a.from_token_address||'').toLowerCase(),to=(a.to_token_address||'').toLowerCase(),usd=Number(a.volume_in_usd);if(!Number.isFinite(usd)||usd<=0)return null;let side=null;if(to===WETH)side='buy';else if(from===WETH)side='sell';else if(a.kind==='buy'||a.kind==='sell')side=a.kind;return side?{id:t.id||`${a.tx_hash||''}:${a.block_number||''}`,at:Date.parse(a.block_timestamp),side,usd,trader:(a.tx_from_address||'').toLowerCase()}:null}
async function position(request){const url=new URL(request.url),cache=caches.default,key=new Request(`${url.origin}/api/position`,request);if(!url.searchParams.has('refresh')){const hit=await cache.match(key);if(hit)return hit}try{const q=`chain_id=8453&account_address=${ACCOUNT}`;const [overview,pnl,yieldData]=await Promise.all([arc(`/accounts/overview?chain_id=8453&account=${ACCOUNT}`),arc(`/accounts/pnl_cost_basis?${q}`),arc(`/accounts/yield_earned?${q}`)]);if(!overview||!Array.isArray(overview.assets))throw new Error('Arcadia account response invalid or account not found');if(!overview.assets.length)throw new Error('Arcadia account has no tracked assets');delete overview.historic_actions;const body=JSON.stringify({account:ACCOUNT,overview,pnl,yield:yieldData,fetchedAt:new Date().toISOString(),source:'Arcadia official API'});const res=new Response(body,{headers:{'content-type':'application/json;charset=UTF-8','cache-control':'public,max-age=10','x-content-type-options':'nosniff'}});await cache.put(key,res.clone());return res}catch(e){return Response.json({error:e instanceof Error?e.message:'Data unavailable'},{status:502,headers:{'cache-control':'no-store'}})}}

async function momentum(request){const url=new URL(request.url),cache=caches.default,key=new Request(`${url.origin}/api/momentum`,request);const hit=await cache.match(key);if(hit)return hit;try{const poolsRaw=await gt(`/networks/base/tokens/${WETH}/pools?page=1`);const pools=(poolsRaw.data||[]).filter(p=>{const b=tokenAddress(p.relationships?.base_token),q=tokenAddress(p.relationships?.quote_token);return (b===WETH&&STABLES.has(q))||(q===WETH&&STABLES.has(b))}).sort((a,b)=>activityScore(b)-activityScore(a)).slice(0,2);if(!pools.length)throw new Error('No liquid WETH markets found');
  const settled=await Promise.allSettled(pools.map(pool=>gt(`/networks/base/pools/${pool.attributes.address}/trades?trade_volume_in_usd_greater_than=0`)));const batches=settled.filter(x=>x.status==='fulfilled').map(x=>x.value),failedPools=settled.length-batches.length;
  if(!batches.length)throw new Error('Live WETH trade feeds did not respond');
  const cutoff=Date.now()-7*60*1000,seen=new Set(),traders=new Set();let buyUsd=0,sellUsd=0,buys=0,sells=0;
  for(const batch of batches)for(const raw of batch.data||[]){const t=parseTrade(raw);if(!t||!Number.isFinite(t.at)||t.at<cutoff||seen.has(t.id))continue;seen.add(t.id);if(t.side==='buy'){buyUsd+=t.usd;buys++}else{sellUsd+=t.usd;sells++}if(t.trader)traders.add(t.trader)}
  const total=buyUsd+sellUsd,hasTrades=buys+sells>0,buyShare=hasTrades?buyUsd/total:null,top=pools[0].attributes||{},price=Number(top.token_price_usd||top.base_token_price_usd||0),m5=Number(top.price_change_percentage?.m5||0),m15=Number(top.price_change_percentage?.m15||0);const response={price,buyUsd,sellUsd,buyShare,netUsd:buyUsd-sellUsd,buys,sells,traders:traders.size,tradeUsd:total,poolCount:pools.length,respondingPools:batches.length,failedPools,hasTrades,estimated:false,windowMinutes:7,priceChange5m:m5,priceChange15m:m15,fetchedAt:new Date().toISOString(),source:'GeckoTerminal verified Base onchain swaps'};const res=Response.json(response,{headers:{'cache-control':'public,max-age=420','x-content-type-options':'nosniff'}});await cache.put(key,res.clone());return res}catch(e){return Response.json({error:e instanceof Error?e.message:'Live onchain market data unavailable'},{status:502,headers:{'cache-control':'no-store'}})}}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/position')return position(request);if(url.pathname==='/api/momentum')return momentum(request);return env.ASSETS.fetch(request)}};
export{activityScore,momentum,parseTrade,tokenAddress};
